apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vllm-mig-demo
  namespace: argocd
spec:
  destination:
    namespace: vllm-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/example-org/argocd-vllm-mig-demo
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
